# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180118_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PH', 'Phone'), ('Ch', 'Chargers'), ('Ca', 'Cases')], max_length=2),
        ),
    ]
